\x\tobin bomb.txt bomb.bin
\x\tobin a.a b.b
\x\tobin init.a init.b
\x\tobin terrain0.a terrain.0
\x\tobin terrain1.a terrain.1
\x\tobin terrain2.a terrain.2
\x\tobin terrain3.a terrain.3
\x\tobin terrain4.a terrain.4
\x\tobin level0.a level.0
\x\tobin level1.a level.1
\x\tobin level2.a level.2
\x\tobin level3.a level.3
\x\tobin level4.a level.4
\x\tobin intro.a intro.0
\x\tobin sound.a sound.b

copy b.b \gorazd\mobile\bomber\bin\
copy init.b \gorazd\mobile\bomber\bin\
copy terrain.0 \gorazd\mobile\bomber\bin\
copy terrain.1 \gorazd\mobile\bomber\bin\
copy terrain.2 \gorazd\mobile\bomber\bin\
copy terrain.3 \gorazd\mobile\bomber\bin\
copy terrain.4 \gorazd\mobile\bomber\bin\
copy level.0 \gorazd\mobile\bomber\bin\
copy level.1 \gorazd\mobile\bomber\bin\
copy level.2 \gorazd\mobile\bomber\bin\
copy level.3 \gorazd\mobile\bomber\bin\
copy level.4 \gorazd\mobile\bomber\bin\
copy intro.0 \gorazd\mobile\bomber\bin\
copy sound.b \gorazd\mobile\bomber\bin\